---
- name: install the phantomjs
  get_url: >
    url={{ phantomjs_url }}
    dest=/usr/local/src/

- name: untar the phantomjs
  unarchive: >
    src=/usr/local/src/{{ tar_name }}
    dest=/usr/local/
    copy=no
  environment:
    LANG: C
    LC_ALL: C
    LC_MESSAGES: C

- name: copy phantomjs to /usr/bin/
  shell: cp /usr/local/{{ dir_name }}/bin/phantomjs /usr/bin
